version: '3.9'

services:
  backend:
    build: .
    container_name: rag_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
      - qdrant
    volumes:
      - .:/app

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data:
